POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Cobol"
}

###

GET http://localhost:3333/courses?orderBy=title

###

GET http://localhost:3333/courses/66ddf6fa-f4fe-4362-99ee-44c12fdb3bdd
